development: &default
  password: 'xxx'
  site_title: "msl12's Blog"
  site_description: 'My personal blog - stay hungry, stay foolish!'
  site_url: 'http://localhost:3000'
  cache_prefix: 'MSL12'

production:
  <<: *default
  site_url: 'http://msl12.cn'